const ListData = [
  {
    id: 1,
    title: 'first object',
    user: 'Charles Davidson',
    description: 'description',
    status: 'opened',
    createdOn: '12/09/2021',
    overdueOn: '14/09/2021',
    formHtml: 'download',
    formData: 'received',
    formArchieve: 'approval',
    amount: 207600,
  },
  {
    id: 2,
    title: 'first object',
    user: 'Arnaud Bezancon',
    description: 'description',
    status: 'closed',
    createdOn: '15/09/2021',
    overdueOn: '18/09/2021',
    formHtml: 'download',
    formData: 'received',
    formArchieve: 'approval',
    amount: 2345,
  },
  {
    id: 3,
    title: 'third object',
    user: 'Tania Bezancon',
    description: 'description',
    status: 'closed',
    createdOn: '30/09/2021',
    overdueOn: '31/09/2021',
    formHtml: 'download',
    formData: 'received',
    formArchieve: 'approval',
    amount: 8378,
  },
  {
    id: 4,
    title: 'first object',
    user: 'Vincent Daribo',
    description: 'description',
    status: 'opened',
    createdOn: '01/09/2021',
    overdueOn: '03/09/2021',
    formHtml: 'download',
    formData: 'received',
    formArchieve: 'approval',
    amount: 1983,
  },
  {
    id: 5,
    title: 'first object',
    user: 'Vincent Daribo',
    description: 'description',
    status: 'closed',
    createdOn: '11/09/2021',
    overdueOn: '12/09/2021',
    formHtml: 'download',
    formData: 'received',
    formArchieve: 'approval',
    amount: 1903,
  },
  {
    id: 6,
    title: 'first object',
    user: 'Vincent Daribo',
    description: 'description',
    status: 'closed',
    createdOn: '13/09/2021',
    overdueOn: '14/09/2021',
    formHtml: 'download',
    formData: 'received',
    formArchieve: 'approval',
    amount: 3628,
  },
  {
    id: 7,
    title: 'first object',
    user: 'Vincent Daribo',
    description: 'description',
    status: 'closed',
    createdOn: '15/09/2021',
    overdueOn: '16/09/2021',
    formHtml: 'download',
    formData: 'received',
    formArchieve: 'approval',
    amount: 8735,
  },
  {
    id: 8,
    title: 'first object',
    user: 'Vincent Daribo',
    description: 'description',
    status: 'opened',
    createdOn: '19/09/2021',
    overdueOn: '21/09/2021',
    formHtml: 'download',
    formData: 'received',
    formArchieve: 'approval',
    amount: 10000,
  },
  {
    id: 9,
    title: 'first object',
    user: 'Vincent Daribo',
    description: 'description',
    status: 'closed',
    createdOn: '16/09/2021',
    overdueOn: '18/09/2021',
    formHtml: 'download',
    formData: 'received',
    formArchieve: 'approval',
    amount: 1873,
  },
  {
    id: 10,
    title: 'first object',
    user: 'Vincent Daribo',
    description: 'description',
    status: 'opened',
    createdOn: '20/09/2021',
    overdueOn: '21/09/2021',
    formHtml: 'download',
    formData: 'received',
    formArchieve: 'approval',
    amount: 7648,
  },
  {
    id: 11,
    title: 'first object',
    user: 'Vincent Daribo',
    description: 'description',
    status: 'closed',
    createdOn: '25/09/2021',
    overdueOn: '29/09/2021',
    formHtml: 'download',
    formData: 'received',
    formArchieve: 'approval',
    amount: 2873,
  },
];

export default ListData;
module.exports = ListData;
